In [22]:
import numpy as np
import cv2 as cv
import sys
import time

In [34]:
def draw_OpticalFlow(img, flow, step=16):
    for y in range(step//2, frame.shape[0], step):
        for x in range(step//2, frame.shape[1], step):
            dx, dy = flow[y,x].astype(np.int32)
            if(dx*dx + dy*dy) > 1 :
                cv.line(img,(x,y),(x+dx, y+dy),(0,0,255),2)
            else:
                cv.line(img,(x,y),(x+dx, y+dy),(0,255,0),2)

In [36]:
cap = cv.VideoCapture(f'data\C_3_10_2_BU_SMB_09-01_16-08-47_CB_RGB_DF2_M2.mp4')
if not cap.isOpened() : sys.exit('카메라 연결 실패')
print(cap.isOpened())


prev = None

while True:
    ret, frame = cap.read()
    print(ret, frame)
    if not ret : sys.exit('프레임 획득 실패')
    
    if prev is None:
        prev=cv.cvtColor(frame,cv.COLOR_BGR2GRAY)
        continue
    
    curr = cv.cvtColor(frame,cv.COLOR_BGR2GRAY)
    flow = cv.calcOpticalFlowFarneback(prev,curr,None,0.5,3,15,3,5,1.2,0)
    
    draw_OpticalFlow(frame, flow)
    cv.imshow('Opticla flow', frame)
    
    prev=curr
    
    key=cv.waitKey(1)
    if key==ord('q'):
        break
    
cap.release()
cv.destroyAllWindows()

True
True [[[179 172 164]
  [179 172 164]
  [176 169 161]
  ...
  [195 199 187]
  [195 199 187]
  [193 197 185]]

 [[176 169 161]
  [176 169 161]
  [175 168 160]
  ...
  [195 199 187]
  [195 199 187]
  [194 198 186]]

 [[174 167 159]
  [175 168 160]
  [175 168 160]
  ...
  [195 199 187]
  [195 199 187]
  [195 199 187]]

 ...

 [[197 193 196]
  [197 193 196]
  [197 193 196]
  ...
  [110 119 125]
  [110 119 125]
  [108 117 123]]

 [[197 193 196]
  [197 193 196]
  [197 193 196]
  ...
  [110 119 125]
  [110 119 125]
  [108 117 123]]

 [[197 193 196]
  [197 193 196]
  [197 193 196]
  ...
  [110 119 125]
  [110 119 125]
  [108 117 123]]]
True [[[176 171 163]
  [176 171 163]
  [173 168 160]
  ...
  [195 198 188]
  [196 199 189]
  [194 197 187]]

 [[174 169 161]
  [176 171 163]
  [176 171 163]
  ...
  [195 198 188]
  [195 198 188]
  [195 198 188]]

 [[178 171 163]
  [178 171 163]
  [176 169 161]
  ...
  [195 198 188]
  [195 198 188]
  [196 199 189]]

 ...

 [[192 194 196]
  [192 194 196]
  [19