In [1]:
import numpy as np
import cv2

In [2]:
src = cv2.imread('./lenna.bmp', cv2.IMREAD_GRAYSCALE)

In [3]:
src.shape

(512, 512)

In [7]:
cv2.imshow('img', src + 100)
cv2.waitKey()
cv2.destroyAllWindows()

In [ ]:
dst = cv2.subtract(src, 100)
cv2.imshow('img', dst)
cv2.waitKey()
cv2.destroyAllWindows()

In [19]:
def update(pos):    
    dst = cv2.add(src, pos)
    cv2.imshow('dst',dst)

In [21]:
cv2.namedWindow('dst')
cv2.createTrackbar('Bright', 'dst',0,100,update) 
update(0)
cv2.waitKey()
cv2.destroyAllWindows()

In [22]:
src = cv2.imread('./lenna.bmp')
cv2.imshow('img', src)
cv2.waitKey()
cv2.destroyAllWindows()

In [23]:
win_name = 'Trackbar'

In [78]:
def onChange(x):                                        
    print(x)                                            # 트랙바 새로운 위치 값 --- ②
    try:
        r = cv2.getTrackbarPos('R',win_name)               
        g = cv2.getTrackbarPos('G',win_name)               
        b = cv2.getTrackbarPos('B',win_name)
    except cv2.error:
        r = g = b = 0
    dst = cv2.add(src,np.array([b,g,r]))
    print(src[:,:,2])                                     # 기존 이미지에 새로운 픽셀 값 적용 --- ④ 
    cv2.imshow(win_name, dst) 

In [79]:
src = cv2.imread('./lenna.bmp')
cv2.imshow(win_name,src)                                

cv2.createTrackbar('R', win_name, 0, 100, onChange)  
cv2.createTrackbar('G', win_name, 0, 100, onChange)
cv2.createTrackbar('B', win_name, 0, 100, onChange)

while True:
    if cv2.waitKey(1) & 0xFF == 27:
        break
cv2.destroyAllWindows()        

1
[[226 226 223 ... 230 221 200]
 [226 226 223 ... 230 221 200]
 [226 226 223 ... 230 221 200]
 ...
 [ 84  84  92 ... 173 172 177]
 [ 82  82  96 ... 179 181 185]
 [ 82  82  96 ... 179 181 185]]
2
[[226 226 223 ... 230 221 200]
 [226 226 223 ... 230 221 200]
 [226 226 223 ... 230 221 200]
 ...
 [ 84  84  92 ... 173 172 177]
 [ 82  82  96 ... 179 181 185]
 [ 82  82  96 ... 179 181 185]]
3
[[226 226 223 ... 230 221 200]
 [226 226 223 ... 230 221 200]
 [226 226 223 ... 230 221 200]
 ...
 [ 84  84  92 ... 173 172 177]
 [ 82  82  96 ... 179 181 185]
 [ 82  82  96 ... 179 181 185]]
4
[[226 226 223 ... 230 221 200]
 [226 226 223 ... 230 221 200]
 [226 226 223 ... 230 221 200]
 ...
 [ 84  84  92 ... 173 172 177]
 [ 82  82  96 ... 179 181 185]
 [ 82  82  96 ... 179 181 185]]
5
[[226 226 223 ... 230 221 200]
 [226 226 223 ... 230 221 200]
 [226 226 223 ... 230 221 200]
 ...
 [ 84  84  92 ... 173 172 177]
 [ 82  82  96 ... 179 181 185]
 [ 82  82  96 ... 179 181 185]]
6
[[226 226 223 ... 230 221 20

In [80]:
a = [1,2,3,4,5,6,7,8]

In [ ]:
np.clip(a,1,2)

array([1, 2, 2, 2, 2, 2, 2, 2])

In [85]:
alpha = 1.0

In [86]:
np.clip(src + ((src-128)* alpha), 0, 255)

array([[[255., 146., 255.],
        [255., 146., 255.],
        [138., 146., 255.],
        ...,
        [255., 168., 255.],
        [255., 132., 255.],
        [255., 255., 255.]],

       [[255., 146., 255.],
        [255., 146., 255.],
        [138., 146., 255.],
        ...,
        [255., 168., 255.],
        [255., 132., 255.],
        [255., 255., 255.]],

       [[255., 146., 255.],
        [255., 146., 255.],
        [138., 146., 255.],
        ...,
        [255., 168., 255.],
        [255., 132., 255.],
        [255., 255., 255.]],

       ...,

       [[248., 164., 255.],
        [248., 164., 255.],
        [244., 182., 255.],
        ...,
        [255., 255., 218.],
        [255., 255., 216.],
        [255., 252., 226.]],

       [[242., 172., 255.],
        [242., 172., 255.],
        [252., 192., 255.],
        ...,
        [255., 255., 230.],
        [255., 255., 234.],
        [255., 255., 242.]],

       [[242., 172., 255.],
        [242., 172., 255.],
        [252., 1

In [108]:
src = cv2.imread('./lenna.bmp',cv2.IMREAD_GRAYSCALE)
dst = np.clip(src + ((src-128.)* alpha), 0, 255).astype('uint8')
cv2.imshow('dst',dst)
cv2.imshow('src',src)
cv2.waitKey()
cv2.destroyAllWindows()

In [ ]:
src = cv2.imread('./img/camera',cv2.IMREAD_GRAYSCALE)

 # 히스토그램 스트레칭


In [132]:
img = cv2.imread('./hawkes.bmp', cv2.IMREAD_GRAYSCALE)

In [133]:
gmin = float(np.min(img))
gmax = float(np.max(img))
print(gmin, gmax)

107.0 218.0


In [134]:
dst = ((img - gmin) * 255. / (gmax - gmin)).astype('uint8')

In [136]:
cv2.imshow('img',dst)
cv2.waitKey()
cv2.destroyAllWindows()

In [137]:
dst = cv2.equalizeHist(img)

In [140]:
def calcGrayHist(img):
    channels = [0]
    histSize = [256]
    histRange = [0, 256]

    hist = cv2.calcHist([img], channels, None, histSize, histRange)

    return hist

In [141]:
def getGrayHistImage(hist):
    histMax = np.max(hist)

    imgHist = np.full((100, 256), 255, dtype=np.uint8)
    for x in range(256):
        pt1 = (x, 100)
        pt2 = (x, 100 - int(hist[x, 0] * 100 / histMax))
        cv2.line(imgHist, pt1, pt2, 0)

    return imgHist

In [143]:
def histgoram_stretching():
    src = cv2.imread('hawkes.bmp', cv2.IMREAD_GRAYSCALE)

    if src is None:
        print('Image load failed!')
        return

    gmin = float(np.min(src))
    gmax = float(np.max(src))

    dst = ((src - gmin) * 255. / (gmax - gmin)).astype(np.uint8)

    cv2.imshow('src', src)
    cv2.imshow('srcHist', getGrayHistImage(calcGrayHist(src)))

    cv2.imshow('dst', dst)
    cv2.imshow('dstHist', getGrayHistImage(calcGrayHist(dst)))

    cv2.waitKey()
    cv2.destroyAllWindows()


In [144]:
def histgoram_equalization():
    src = cv2.imread('hawkes.bmp', cv2.IMREAD_GRAYSCALE)

    if src is None:
        print('Image load failed!')
        return

    dst = cv2.equalizeHist(src)

    cv2.imshow('src', src)
    cv2.imshow('srcHist', getGrayHistImage(calcGrayHist(src)))

    cv2.imshow('dst', dst)
    cv2.imshow('dstHist', getGrayHistImage(calcGrayHist(dst)))

    cv2.waitKey()
    cv2.destroyAllWindows()

In [ ]:
getGrayHistImage(calcGrayHist(img))

array([[255, 255, 255, ..., 255, 255, 255],
       [255, 255, 255, ..., 255, 255, 255],
       [255, 255, 255, ..., 255, 255, 255],
       ...,
       [255, 255, 255, ..., 255, 255, 255],
       [255, 255, 255, ..., 255, 255, 255],
       [255, 255, 255, ..., 255, 255, 255]], shape=(100, 256), dtype=uint8)

In [154]:
histgoram_equalization()
cv2.waitKey()
cv2.destroyAllWindows()